/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.javapro.quizadmin;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import static org.javapro.quizadmin.QuestionParser.parseQuestion;

/**
 *
 * @author RuslanLopez
 */
public class QuizAdmin extends JFrame implements ActionListener {

    private List<Question> questions = new ArrayList<>();
    private Optional<Question> preguntaActual;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton agregarOpcion;
    JButton btnAgregarPregunta;
    JButton btnAnterior;
    JComboBox<String> btnIrAUnaEspecífica;
    JButton btnQuitarPregunta;
    JButton btnSiguente;
    JComboBox<String> cmbTipoPregunta;
    JPanel jPanel1;
    JLabel lblEnunciado;
    JLabel lblOpciones;
    JLabel lblRespuesta;
    JLabel lblTipoPregunta;
    JPanel opcionespnl;
    ButtonGroup optionButtonsGroup;
    JPanel pnlControles;
    JPanel pnlDatosPregunta;
    JPanel pnlOpciones;
    JScrollPane pnlOpcionesRespuesta;
    JPanel pnlQuestionCreationDeletion;
    JPanel pnlQuestionNavigation;
    JPanel pnlRespuesta;
    JPanel pnleditarOpciones;
    JPanel pnlenunciadoPregunta;
    JButton quitarOpcion;
    JPanel respuestapnl;
    JScrollPane scrollBlancos;
    JTextField txtEnunciado;
    JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form QuizAdmin
     */
    public QuizAdmin() {
        initComponents();
        // TODO add jfilechooser to open and edit a file
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        optionButtonsGroup = new ButtonGroup();
        pnlDatosPregunta = new JPanel();
        pnlenunciadoPregunta = new JPanel();
        lblEnunciado = new JLabel();
        txtEnunciado = new JTextField();
        lblTipoPregunta = new JLabel();
        cmbTipoPregunta = new JComboBox<>();
        opcionespnl = new JPanel();
        lblOpciones = new JLabel();
        //lblOpciones.setVisible(false);
        //lblOpciones.setBounds(0, 0, 0, 0);
        pnlOpciones = new JPanel();
        //pnlOpciones.setVisible(false);
        //lblOpciones.setBounds(0, 0, 0, 0);
        pnlOpcionesRespuesta = new JScrollPane();
        jPanel1 = new JPanel();
        pnleditarOpciones = new JPanel();
        agregarOpcion = new JButton();
        quitarOpcion = new JButton();
        respuestapnl = new JPanel();
        lblRespuesta = new JLabel();
        pnlRespuesta = new JPanel();
        scrollBlancos = new JScrollPane();
        txtRespuesta = new JTextArea();
        pnlControles = new JPanel();
        pnlQuestionCreationDeletion = new JPanel();
        btnQuitarPregunta = new JButton();
        btnAgregarPregunta = new JButton();
        pnlQuestionNavigation = new JPanel();
        btnAnterior = new JButton();
        btnSiguente = new JButton();
        btnIrAUnaEspecífica = new JComboBox<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ResourceBundle bundle = ResourceBundle.getBundle("org/javapro/quizadmin/Bundle"); // NOI18N
        pnlDatosPregunta.setBorder(BorderFactory.createTitledBorder(bundle.getString("QuizAdmin.pnlDatosPregunta.border.title"))); // NOI18N
        pnlDatosPregunta.setLayout(new BoxLayout(pnlDatosPregunta, BoxLayout.Y_AXIS));

        pnlenunciadoPregunta.setLayout(new GridLayout(0, 2));

        lblEnunciado.setText(bundle.getString("QuizAdmin.lblEnunciado.text")); // NOI18N
        pnlenunciadoPregunta.add(lblEnunciado);
        pnlenunciadoPregunta.add(txtEnunciado);

        lblTipoPregunta.setText(bundle.getString("QuizAdmin.lblTipoPregunta.text")); // NOI18N
        pnlenunciadoPregunta.add(lblTipoPregunta);

        cmbTipoPregunta.setModel(new DefaultComboBoxModel<>(new String[] { "Llenar el espacio en blanco", "Opción Múltiple", "Respuesta Múltiple" }));
        pnlenunciadoPregunta.add(cmbTipoPregunta);

        pnlDatosPregunta.add(pnlenunciadoPregunta);

        opcionespnl.setLayout(new BoxLayout(opcionespnl, BoxLayout.LINE_AXIS));

        lblOpciones.setText(bundle.getString("QuizAdmin.lblOpciones.text")); // NOI18N
        opcionespnl.add(lblOpciones);

        pnlOpciones.setLayout(new GridBagLayout());

        pnlOpcionesRespuesta.setMinimumSize(new Dimension(125, 125));

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        pnlOpcionesRespuesta.setViewportView(jPanel1);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        pnlOpciones.add(pnlOpcionesRespuesta, gridBagConstraints);

        pnleditarOpciones.setLayout(new BoxLayout(pnleditarOpciones, BoxLayout.Y_AXIS));

        agregarOpcion.setText(bundle.getString("QuizAdmin.agregarOpcion.text")); // NOI18N
        agregarOpcion.setEnabled(false);
        pnleditarOpciones.add(agregarOpcion);

        quitarOpcion.setText(bundle.getString("QuizAdmin.quitarOpcion.text")); // NOI18N
        quitarOpcion.setEnabled(false);
        pnleditarOpciones.add(quitarOpcion);

        pnlOpciones.add(pnleditarOpciones, new GridBagConstraints());

        opcionespnl.add(pnlOpciones);

        pnlDatosPregunta.add(opcionespnl);

        respuestapnl.setLayout(new FlowLayout(FlowLayout.LEFT));

        lblRespuesta.setText(bundle.getString("QuizAdmin.lblRespuesta.text")); // NOI18N
        respuestapnl.add(lblRespuesta);

        pnlRespuesta.setMinimumSize(new Dimension(100, 90));
        pnlRespuesta.setPreferredSize(new Dimension(200, 90));
        pnlRespuesta.setLayout(new BorderLayout());

        txtRespuesta.setEditable(false);
        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        scrollBlancos.setViewportView(txtRespuesta);

        pnlRespuesta.add(scrollBlancos, BorderLayout.CENTER);

        respuestapnl.add(pnlRespuesta);

        pnlDatosPregunta.add(respuestapnl);

        getContentPane().add(pnlDatosPregunta, BorderLayout.CENTER);

        pnlControles.setBorder(BorderFactory.createTitledBorder(bundle.getString("QuizAdmin.pnlControles.border.title"))); // NOI18N
        pnlControles.setLayout(new BorderLayout());

        pnlQuestionCreationDeletion.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlQuestionCreationDeletion.setLayout(new BorderLayout());

        btnQuitarPregunta.setText(bundle.getString("QuizAdmin.btnQuitarPregunta.text")); // NOI18N
        btnQuitarPregunta.setEnabled(false);
        btnQuitarPregunta.addActionListener(this);
        pnlQuestionCreationDeletion.add(btnQuitarPregunta, BorderLayout.EAST);

        btnAgregarPregunta.setText(bundle.getString("QuizAdmin.btnAgregarPregunta.text")); // NOI18N
        btnAgregarPregunta.setEnabled(false);
        btnAgregarPregunta.addActionListener(this);
        pnlQuestionCreationDeletion.add(btnAgregarPregunta, BorderLayout.WEST);

        pnlControles.add(pnlQuestionCreationDeletion, BorderLayout.NORTH);

        pnlQuestionNavigation.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlQuestionNavigation.setLayout(new BorderLayout());

        btnAnterior.setText(bundle.getString("QuizAdmin.btnAnterior.text")); // NOI18N
        btnAnterior.setEnabled(false);
        btnAnterior.addActionListener(this);
        pnlQuestionNavigation.add(btnAnterior, BorderLayout.WEST);

        btnSiguente.setText(bundle.getString("QuizAdmin.btnSiguente.text")); // NOI18N
        btnSiguente.setEnabled(false);
        btnSiguente.addActionListener(this);
        pnlQuestionNavigation.add(btnSiguente, BorderLayout.EAST);

        btnIrAUnaEspecífica.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        btnIrAUnaEspecífica.setEnabled(false);
        pnlQuestionNavigation.add(btnIrAUnaEspecífica, BorderLayout.CENTER);

        pnlControles.add(pnlQuestionNavigation, BorderLayout.CENTER);

        getContentPane().add(pnlControles, BorderLayout.PAGE_END);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == btnSiguente) {
            QuizAdmin.this.btnSiguenteActionPerformed(evt);
        }
        else if (evt.getSource() == btnAgregarPregunta) {
            QuizAdmin.this.btnAgregarPreguntaActionPerformed(evt);
        }
        else if (evt.getSource() == btnAnterior) {
            QuizAdmin.this.btnAnteriorActionPerformed(evt);
        }
        else if (evt.getSource() == btnQuitarPregunta) {
            QuizAdmin.this.btnQuitarPreguntaActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguenteActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSiguenteActionPerformed
        // TODO pasar al siguiente elemento de las opciones de respuesta
        pintaPreguntaActual();
    }//GEN-LAST:event_btnSiguenteActionPerformed

    private void btnAgregarPreguntaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaActionPerformed
        //TODO mostrar un dialogo para preguntar el tipo de pregunta a agregar
    }//GEN-LAST:event_btnAgregarPreguntaActionPerformed

    private void btnAnteriorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO pasar al anterior elemento de las opciones de respuesta
        pintaPreguntaActual();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnQuitarPreguntaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnQuitarPreguntaActionPerformed
        // TODO add your handling code here:
        preguntaActual.ifPresent((actual)->{
            int currentIndex = questions.indexOf(actual);
            final int size = questions.size();

            if (size == 1) {
                questions.remove(actual);
                //preguntaActual.ifPresent(questions::remove);
                preguntaActual = Optional.empty();
            } else {
                questions.remove(actual);
                //preguntaActual.ifPresent(questions::remove);
                preguntaActual = Optional.of(questions.get(currentIndex == 0 ? 1 : currentIndex - 1));
            }
            pintaPreguntaActual();
        });
    }//GEN-LAST:event_btnQuitarPreguntaActionPerformed

    public void loadQuestionsFromFile(String aFile) throws FileNotFoundException, IOException{
        try(BufferedReader reader = new BufferedReader(new FileReader(new File(aFile)))){
            parseQuestions(reader);
        }
    }

    public void parseQuestions(BufferedReader reader) throws IOException {
        String thisLine;
        while ((thisLine = reader.readLine()) != null) {
            questions.add(parseQuestion(thisLine));
        }
        if(questions.size()>1){
           btnSiguente.setEnabled(true);
        }
        preguntaActual = Optional.of(questions.get(0));
        pintaPreguntaActual();
    }

    private void pintaPreguntaActual() {
        System.out.println("Pintando pregunta actual:"+preguntaActual);
        btnQuitarPregunta.setEnabled(!questions.isEmpty());
        
        preguntaActual.ifPresent(pregunta->{
            txtEnunciado.setText(pregunta.getText());
            QuestionType preguntaType = pregunta.getType();
            cmbTipoPregunta.setSelectedIndex(preguntaType.ordinal());
            switch (preguntaType) {
                case FILL_IN_THE_BLANKS:
                    FillBlankQuestion fb = (FillBlankQuestion) pregunta;
                    SwingUtilities.invokeLater(() -> {
                        eliminaOpcionesDeRespuestaPrevias();
                        agregarOpcion.setEnabled(false);
                        quitarOpcion.setEnabled(false);
                        txtRespuesta.setText(fb.getAnswer());
                        pnlOpciones.revalidate();
                        pnlOpciones.repaint();
                    });
                    
                    //TODO ocultar panel de opción
                    break;
                case MULTIPLE_OPTION:
                    eliminaOpcionesDeRespuestaPrevias();
                    agregarOpcion.setEnabled(true);
                    quitarOpcion.setEnabled(true);
                    MultipleChoiceQuestion mc = (MultipleChoiceQuestion) pregunta;
                    SwingUtilities.invokeLater(() -> {
                    mc.getChoices()
                            .stream()
                            .forEachOrdered((option) -> {
                                final JRadioButton jRadioButton = new JRadioButton(option);
                                optionButtonsGroup.add(jRadioButton);
                                jPanel1.add(jRadioButton);
                            });
                        pnlOpciones.revalidate();
                        pnlOpciones.repaint();
                    });

                    //TODO ocultar panel de respuesta
                    //TODO preseleccionar la opción de respuesta correcta
                    break;
                case MULTIPLE_ANSWER:
                    MultipleAnswerQuestion ma = (MultipleAnswerQuestion) pregunta;
                    SwingUtilities.invokeLater(() -> {
                    eliminaOpcionesDeRespuestaPrevias();
                    agregarOpcion.setEnabled(true);
                    quitarOpcion.setEnabled(true);
                    ma.getChoices()
                            .stream()
                            .forEachOrdered(check -> {
                                final JCheckBox jCheckBox = new JCheckBox(check);
                                optionButtonsGroup.add(jCheckBox);
                                jPanel1.add(jCheckBox);
                            });
                        pnlOpciones.revalidate();
                        pnlOpciones.repaint();
                    });
                    //TODO ocultar panel de respuesta
                    //TODO preseleccionar las opciones de respuesta correcta
                    break;
                default:
                    System.err.println("unexpected question type");
            }
        });
        
    }

    private void eliminaOpcionesDeRespuestaPrevias() {
        Collections.list(optionButtonsGroup.getElements()).stream().forEach(optionButtonsGroup::remove);
        jPanel1.removeAll();
    }


}
